import 'package:cloudinary_public/cloudinary_public.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:mobile/core/services/cloudinary_config.dart';
import 'package:mobile/features/auth/data/models/user_model.dart';
import 'package:mobile/features/booking/data/models/review_model.dart';
import 'package:mobile/features/booking/data/repositories/review_repository.dart';

class ReviewViewModel extends ChangeNotifier {
  final ReviewRepository _reviewRepository = ReviewRepository();

  double _rating = 5.0;
  String _comment = '';
  final List<String> _images = [];
  bool _isSubmitting = false;
  String? _error;

  double get rating => _rating;
  String get comment => _comment;
  List<String> get images => _images;
  bool get isSubmitting => _isSubmitting;
  String? get error => _error;

  void setRating(double value) {
    _rating = value;
    notifyListeners();
  }

  void setComment(String value) {
    _comment = value;
    notifyListeners();
  }

  Future<void> pickImage() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery, imageQuality: 70);

    if (pickedFile != null) {
      _isSubmitting = true;
      notifyListeners();
      try {
        final cloudinary = CloudinaryPublic(
          CloudinaryConfig.cloudName,
          CloudinaryConfig.uploadPreset,
          cache: false,
        );
        CloudinaryResponse response = await cloudinary.uploadFile(
          CloudinaryFile.fromFile(pickedFile.path, folder: 'reviews'),
        );
        _images.add(response.secureUrl);
      } catch (e) {
        _error = "Lỗi khi tải ảnh lên: $e";
      } finally {
        _isSubmitting = false;
        notifyListeners();
      }
    }
  }

  void removeImage(int index) {
    _images.removeAt(index);
    notifyListeners();
  }

  Future<bool> submitReview({
    required String bookingId,
    required String providerId,
    required UserModel currentUser,
  }) async {
    if (_comment.isEmpty) {
      _error = "Vui lòng để lại nhận xét.";
      notifyListeners();
      return false;
    }

    _isSubmitting = true;
    _error = null;
    notifyListeners();

    try {
      final review = ReviewModel(
        id: '', // Will be generated by Firestore
        bookingId: bookingId,
        customerId: currentUser.uid,
        providerId: providerId,
        customerName: currentUser.fullName,
        customerAvatar: currentUser.avatarUrl,
        rating: _rating,
        comment: _comment,
        images: _images,
        createdAt: DateTime.now(),
      );

      await _reviewRepository.submitReview(review);
      return true;
    } catch (e) {
      _error = e.toString();
      return false;
    } finally {
      _isSubmitting = false;
      notifyListeners();
    }
  }

  void clear() {
    _rating = 5.0;
    _comment = '';
    _images.clear();
    _isSubmitting = false;
    _error = null;
  }
}
